on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: desarrollo
 
jobs:
  sonarqube:
    name: "Cual sera el valor de la variable"
    environment: Desa
    runs-on: ubuntu-latest
    steps:
      - name: "Environment"
        id: echoenv
        run: echo "yeison ${{ env.YEISON }} "
