on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: main
env: 
  env_novar: ${{vars.NOYEISON }}
  env_var: ${{vars.YEISON }}
jobs:
   aca:
    name: "Cual sera el valor de la variable"
    environment: Desa
    runs-on: ubuntu-latest
    steps:
      - name: "YEISON"
        id: echoenv
        run: echo "yeison $env.YEISON  env_var $env_var"
        env:
          env_var: ${{vars.YEISON }}
      - name: "NOYEISON"
        id: echoenvno
        run: echo "noyeison $env.NOYEISON  env_novar $env_novar"
        env:
          env_var: ${{vars.NOYEISON }}
